### ISSUE TITLE
mysql_grant failing to grant permission since version 3.0.23 on mysql 8.0.28 (with partial revokes ON)

### ISSUE THREAD

**Issue by av-mathiaspius** [petoju/terraform-provider-mysql#47] opened 2022-11-10 19:21 UTC
Hi there, I've encountered an issue on versions 3.0.23+ targeting mysql 8.0.28 with partial_revokes on, where attempting to create even narrowly defined grants fails. 3.0.22 and earlier appear to work fine.

### Terraform Version
Terraform v1.2.4 on linux_amd64
petoju/mysql 3.0.23+

### Affected Resource(s)
- mysql_grant

### Terraform Configuration Files
```hcl
resource "mysql_grant" "this" {
  user       = "dbusername"
  host       = "%"
  database   = "databasename"
  privileges = ["SELECT"]
}
```

### Debug Output
I'll include the abbreviated debug output, since I'm somewhat certain where the issue is occurring:
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to mysql_grant.this, provider
│ "provider[\"registry.terraform.io/petoju/mysql\"]" produced an unexpected
│ new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
With TF_LOG=trace enabled, this also appears in the log:
```
2022-11-10T19:03:33.657Z [INFO]  provider.terraform-provider-mysql_v3.0.23: 2022/11/10 19:03:33 Executing statement: GRANT SELECT ON `databasename`.* TO 'dbusername'@'%': timestamp=2022-11-10T19:03:33.657Z
2022-11-10T19:03:33.700Z [INFO]  provider.terraform-provider-mysql_v3.0.23: 2022/11/10 19:03:33 [WARN] GRANT not found for 'dbusername'@'%' (%!s(<nil>)) - removing from state: timestamp=2022-11-10T19:03:33.700Z
```
More context [here](https://gist.github.com/av-mathiaspius/3025fcd2f4bf8ecee08941c02be02227)

### Expected Behavior
I expected the grant to be created.

### Actual Behavior
The above error occurred.

### Steps to Reproduce
Attempt to create the `mysql_grant` as described above on a MySQL 8.0.28 instance with `partial_revokes = ON` using a version of the provider equal to or newer than 3.0.23.

### Important Factoids
I was able to narrow the issue down to the change between 3.0.22 and 3.0.23. That is to say, 3.0.22 works as expected, but 3.0.23 and 3.0.24 crashes as shown above. I haven't had time to dive into the deeper logic surrounding this, but a cursory glance suggests maybe [this section](https://github.com/petoju/terraform-provider-mysql/compare/v3.0.22...v3.0.23?diff=split#diff-b410da4f476967e3ec280701a3dcf72108093885403a52fe2753d8706a6c0d72R299-R302) of the diff could be the culprit. It looks like the scope might be closing before the following code, rather than encompassing it, meaning the grant length code proceeds, even if an error has occurred.

### References
Seems to be related to, or a continuation of the `partial_revoke`issues identified in this issue: https://github.com/petoju/terraform-provider-mysql/issues/3

**Comment by av-mathiaspius** [comment] 2022-11-15 12:05
Here's the partial_revokes from the database I am using:
```
MySQL [(none)]> select @@global.partial_revokes;
+--------------------------+
| @@global.partial_revokes |
+--------------------------+
|                        1 |
+--------------------------+
1 row in set (0.018 sec)
```
I just tried running your terraform against the database again, only changing the provider. Here's the gist with the logs from the respective runs: https://gist.github.com/av-mathiaspius/e01775f4430f2bfe19e5761f67915bce

The database in question is provided by a third party, so I can't rule out that there's some kind of configuration setting or privilege which my user is missing, which is causing this issue.

**Comment by etchevef** [comment] 2023-01-26 17:10
I just got the exact same error happen to me, with :

 ```
 % terraform version
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/helm v2.8.0
+ provider registry.terraform.io/ovh/ovh v0.26.0
+ provider registry.terraform.io/petoju/mysql v3.0.28
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.49.0
```
mysql version 8, deployed by OVH.

I did manage to manually grant privilege with the same configured user with : 
```
MySQL [(none)]> GRANT ALL PRIVILEGES ON maela_identity.* to 'user_identity'@'%' WITH GRANT OPTION;
MySQL [(none)]> show grants for user_identity;
+-------------------------------------------------------------------------------------+
| Grants for user_identity@%                                                          |
+-------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO "user_identity"@"%"                                           |
| GRANT ALL PRIVILEGES ON "maela_identity".* TO "user_identity"@"%" WITH GRANT OPTION |
+-------------------------------------------------------------------------------------+
```
so it looks like it should work

**Comment by petoju** [comment] 2023-01-26 17:30
To debug this, we need at least some of these:
1. At least somewhat skilled programmed to try the exact query and find the cause. Ideally someone able to write a simple test case with docker-compose.
2. Configuration you are trying to apply.
3. Terraform logs showing what was executed.
4. State of MySQL before and after applying terraform. That means grants via `SHOW GRANTS FOR ...`. The identity after FOR should match whatever is provided in your configuration.
5. Manual execution of GRANT if it does not work.

Especially, I have no idea, where the issue is:
a) is it when GRANTing rights?
b) is it when verifying the GRANT is in place?

**Comment by petoju** [comment] 2023-01-27 18:41
@etchevef thanks for the logs and all the commands. It looks double quotes could be to blame.

I released provider 3.0.29, that should fix that and it also adds more detailed logging so we should be able to pinpoint the issue. Or at least come closer to it.

Could you test it, please?

**Comment by etchevef** [comment] 2023-01-30 09:21
Yup, upgrade to 3.0.29 solved the problem. Thanks for your reactivity !

**Comment by petoju** [comment] 2023-01-30 13:47
@etchevef also thanks for assistance!
Closing.

**Closed by petoju** 2023-01-30 13:47 UTC
